; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=openmp-opt -S < %s | FileCheck %s --check-prefixes=CHECK,DEFAULT
; RUN: opt -passes=openmp-opt -openmp-opt-max-callees-for-specialization=4 -S < %s | FileCheck %s --check-prefixes=CHECK,CAP4
; The bound is a threshold on the call site, not a limit on how many callees get
; specialized: @three gets its if-cascade of direct calls, and @four keeps its
; indirect call rather than getting three direct calls and a fallback. Raising
; the bound to 4 brings @four in.

target triple = "amdgcn-amd-amdhsa"

@g = external global i32

define internal void @c1() {
;
;
;
; CHECK-LABEL: define internal void @c1(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    store volatile i32 1, ptr @g, align 4
; CHECK-NEXT:    ret void
;
  store volatile i32 1, ptr @g
  ret void
}

define internal void @c2() {
;
;
;
; CHECK-LABEL: define internal void @c2(
; CHECK-SAME: ) #[[ATTR0]] {
; CHECK-NEXT:    store volatile i32 2, ptr @g, align 4
; CHECK-NEXT:    ret void
;
  store volatile i32 2, ptr @g
  ret void
}

define internal void @c3() {
;
;
;
; CHECK-LABEL: define internal void @c3(
; CHECK-SAME: ) #[[ATTR0]] {
; CHECK-NEXT:    store volatile i32 3, ptr @g, align 4
; CHECK-NEXT:    ret void
;
  store volatile i32 3, ptr @g
  ret void
}

define internal void @c4() {
;
;
;
; CHECK-LABEL: define internal void @c4(
; CHECK-SAME: ) #[[ATTR0]] {
; CHECK-NEXT:    store volatile i32 4, ptr @g, align 4
; CHECK-NEXT:    ret void
;
  store volatile i32 4, ptr @g
  ret void
}

define void @three(i1 %a, i1 %b) {
;
;
;
; CHECK-LABEL: define void @three(
; CHECK-SAME: i1 [[A:%.*]], i1 [[B:%.*]]) {
; CHECK-NEXT:    [[S0:%.*]] = select i1 [[A]], ptr @c1, ptr @c2
; CHECK-NEXT:    [[S1:%.*]] = select i1 [[B]], ptr [[S0]], ptr @c3
; CHECK-NEXT:    call void [[S1]]() #[[ATTR0]]
; CHECK-NEXT:    ret void
;
  %s0 = select i1 %a, ptr @c1, ptr @c2
  %s1 = select i1 %b, ptr %s0, ptr @c3
  call void %s1()
  ret void
}

define void @four(i1 %a, i1 %b, i1 %c) {
;
;
;
; CHECK-LABEL: define void @four(
; CHECK-SAME: i1 [[A:%.*]], i1 [[B:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:    [[S0:%.*]] = select i1 [[A]], ptr @c1, ptr @c2
; CHECK-NEXT:    [[S1:%.*]] = select i1 [[B]], ptr [[S0]], ptr @c3
; CHECK-NEXT:    [[S2:%.*]] = select i1 [[C]], ptr [[S1]], ptr @c4
; CHECK-NEXT:    call void [[S2]]() #[[ATTR0]]
; CHECK-NEXT:    ret void
;
  %s0 = select i1 %a, ptr @c1, ptr @c2
  %s1 = select i1 %b, ptr %s0, ptr @c3
  %s2 = select i1 %c, ptr %s1, ptr @c4
  call void %s2()
  ret void
}

!llvm.module.flags = !{!0, !1}

!0 = !{i32 7, !"openmp", i32 50}
!1 = !{i32 7, !"openmp-device", i32 50}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CAP4: {{.*}}
; DEFAULT: {{.*}}
